#!/usr/bin/env python3
# python3 generate.py <dataset_dir> <pair_input> <output_dir> <records_out> -> AdvFaceGAN-style dual-identity probes

from __future__ import annotations

import argparse
import json
import math
import random
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image

try:
    from facenet_pytorch import InceptionResnetV1
except ImportError as exc:  # pragma: no cover - dependency is optional at import time
    InceptionResnetV1 = None
    FACENET_IMPORT_ERROR = exc
else:
    FACENET_IMPORT_ERROR = None


DEFAULT_IMAGE_SIZE = 112
DEFAULT_MAX_PERTURBATION = 0.12
DEFAULT_STEPS = 120
DEFAULT_LR = 0.02
DEFAULT_SOURCE_WEIGHT = 1.0
DEFAULT_TARGET_WEIGHT = 1.35
DEFAULT_SOURCE_PIXEL_WEIGHT = 12.0
DEFAULT_TARGET_PIXEL_WEIGHT = 1.5
DEFAULT_TV_WEIGHT = 0.002
DEFAULT_BALANCE_WEIGHT = 0.1


@dataclass
class PairRecord:
    index: int
    victim_identity: str
    attacker_identity: str
    victim_image: str
    attacker_image: str
    output_image: str
    status: str
    message: str
    source_similarity: float | None = None
    target_similarity: float | None = None
    perturbation_linf: float | None = None


class ResidualBlock(nn.Module):
    def __init__(self, channels: int) -> None:
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(channels, channels, kernel_size=3, stride=1, padding=1, bias=False),
            nn.InstanceNorm2d(channels, affine=True),
            nn.ReLU(inplace=True),
            nn.Conv2d(channels, channels, kernel_size=3, stride=1, padding=1, bias=False),
            nn.InstanceNorm2d(channels, affine=True),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return x + self.block(x)


class AdvFaceGANGenerator(nn.Module):
    #based on paper architecture
    def __init__(self, in_channels: int = 6, base_channels: int = 64, num_blocks: int = 6) -> None:
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Conv2d(in_channels, base_channels, kernel_size=7, stride=1, padding=3, bias=False),
            nn.InstanceNorm2d(base_channels, affine=True),
            nn.ReLU(inplace=True),
            nn.Conv2d(base_channels, base_channels * 2, kernel_size=4, stride=2, padding=1, bias=False),
            nn.InstanceNorm2d(base_channels * 2, affine=True),
            nn.ReLU(inplace=True),
            nn.Conv2d(base_channels * 2, base_channels * 4, kernel_size=4, stride=2, padding=1, bias=False),
            nn.InstanceNorm2d(base_channels * 4, affine=True),
            nn.ReLU(inplace=True),
        )
        self.residual = nn.Sequential(*[ResidualBlock(base_channels * 4) for _ in range(num_blocks)])
        self.decoder = nn.Sequential(
            nn.ConvTranspose2d(base_channels * 4, base_channels * 2, kernel_size=4, stride=2, padding=1, bias=False),
            nn.InstanceNorm2d(base_channels * 2, affine=True),
            nn.ReLU(inplace=True),
            nn.ConvTranspose2d(base_channels * 2, base_channels, kernel_size=4, stride=2, padding=1, bias=False),
            nn.InstanceNorm2d(base_channels, affine=True),
            nn.ReLU(inplace=True),
            nn.Conv2d(base_channels, 3, kernel_size=7, stride=1, padding=3, bias=True),
            nn.Tanh(),
        )

    def forward(self, source: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
        stacked = torch.cat([source, target], dim=1)
        features = self.encoder(stacked)
        features = self.residual(features)
        return self.decoder(features)


class FaceNetEmbedder(nn.Module):
    def __init__(self, device: torch.device) -> None:
        super().__init__()
        if InceptionResnetV1 is None:
            raise ImportError(
                "facenet_pytorch is needed for AdvFaceGAN native generation"
            ) from FACENET_IMPORT_ERROR
        self.model = InceptionResnetV1(pretrained="vggface2").eval().to(device)
        for param in self.model.parameters():
            param.requires_grad_(False)

    def forward(self, image_tensor: torch.Tensor) -> torch.Tensor:
        embeddings = self.model(image_tensor)
        return F.normalize(embeddings, p=2, dim=1)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Native AdvFaceGAN-style attack dataset generator.")
    parser.add_argument("dataset_dir", type=str, help="Kept for the project-wide generator contract.")
    parser.add_argument("pair_input", type=str, help="NPZ generated by Attack/pairs.py")
    parser.add_argument("output_dir", type=str, help="Output dataset root")
    parser.add_argument("records_out", type=str, help="JSON record file for generation results")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--device", type=str, default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--image-size", type=int, default=DEFAULT_IMAGE_SIZE)
    parser.add_argument("--steps", type=int, default=DEFAULT_STEPS)
    parser.add_argument("--lr", type=float, default=DEFAULT_LR)
    parser.add_argument("--max-perturbation", type=float, default=DEFAULT_MAX_PERTURBATION)
    parser.add_argument("--source-weight", type=float, default=DEFAULT_SOURCE_WEIGHT)
    parser.add_argument("--target-weight", type=float, default=DEFAULT_TARGET_WEIGHT)
    parser.add_argument("--source-pixel-weight", type=float, default=DEFAULT_SOURCE_PIXEL_WEIGHT)
    parser.add_argument("--target-pixel-weight", type=float, default=DEFAULT_TARGET_PIXEL_WEIGHT)
    parser.add_argument("--tv-weight", type=float, default=DEFAULT_TV_WEIGHT)
    parser.add_argument("--balance-weight", type=float, default=DEFAULT_BALANCE_WEIGHT)
    parser.add_argument("--generator-checkpoint", type=str, default=None)
    parser.add_argument("--jpeg-quality", type=int, default=95)
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_pair_rows(pair_input: Path) -> list[dict[str, str]]:
    data = np.load(pair_input, allow_pickle=True)
    required = ("victim_identity", "attacker_identity", "victim_image", "attacker_image")
    missing = [key for key in required if key not in data.files]
    if missing:
        raise ValueError(f"attack pair input missing required keys {missing}: {pair_input}")

    rows: list[dict[str, str]] = []
    for victim_identity, attacker_identity, victim_image, attacker_image in zip(
        data["victim_identity"].tolist(),
        data["attacker_identity"].tolist(),
        data["victim_image"].tolist(),
        data["attacker_image"].tolist(),
    ):
        rows.append({
            "victim_identity": str(victim_identity),
            "attacker_identity": str(attacker_identity),
            "victim_image": str(Path(victim_image).resolve()),
            "attacker_image": str(Path(attacker_image).resolve()),
        })
    return rows


def load_image(path: Path, image_size: int, device: torch.device) -> torch.Tensor:
    image = Image.open(path).convert("RGB")
    image = image.resize((image_size, image_size), Image.Resampling.BICUBIC)
    array = np.asarray(image, dtype=np.float32) / 255.0
    tensor = torch.from_numpy(array).permute(2, 0, 1).unsqueeze(0)
    tensor = tensor * 2.0 - 1.0
    return tensor.to(device)


def save_image(tensor: torch.Tensor, path: Path, jpeg_quality: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    array = tensor.detach().cpu().squeeze(0).permute(1, 2, 0).clamp(-1.0, 1.0).numpy()
    array = ((array + 1.0) * 0.5 * 255.0).round().astype(np.uint8)
    image = Image.fromarray(array, mode="RGB")
    suffix = path.suffix.lower()
    if suffix in {".jpg", ".jpeg"}:
        image.save(path, quality=max(1, min(100, jpeg_quality)))
    else:
        image.save(path)


def cosine_similarity(emb_a: torch.Tensor, emb_b: torch.Tensor) -> torch.Tensor:
    return torch.sum(F.normalize(emb_a, dim=1) * F.normalize(emb_b, dim=1), dim=1)


def total_variation_loss(delta: torch.Tensor) -> torch.Tensor:
    horizontal = torch.mean(torch.abs(delta[:, :, :, 1:] - delta[:, :, :, :-1]))
    vertical = torch.mean(torch.abs(delta[:, :, 1:, :] - delta[:, :, :-1, :]))
    return horizontal + vertical


def optimize_dual_identity_image(
    source: torch.Tensor,
    target: torch.Tensor,
    embedder: nn.Module,
    *,
    steps: int,
    lr: float,
    max_perturbation: float,
    source_weight: float,
    target_weight: float,
    source_pixel_weight: float,
    target_pixel_weight: float,
    tv_weight: float,
    balance_weight: float,
) -> tuple[torch.Tensor, dict[str, float]]:
    with torch.no_grad():
        source_embedding = embedder(source)
        target_embedding = embedder(target)

    delta_param = torch.zeros_like(source, requires_grad=True)
    optimizer = torch.optim.Adam([delta_param], lr=lr)

    best_adv = source.detach().clone()
    best_stats = {
        "objective": math.inf,
        "source_similarity": float(cosine_similarity(source_embedding, source_embedding).item()),
        "target_similarity": float(cosine_similarity(source_embedding, target_embedding).item()),
        "perturbation_linf": 0.0,
    }

    for _ in range(max(1, steps)):
        delta = torch.tanh(delta_param) * max_perturbation
        adv = torch.clamp(source + delta, min=-1.0, max=1.0)
        adv_embedding = embedder(adv)

        source_similarity = cosine_similarity(adv_embedding, source_embedding)
        target_similarity = cosine_similarity(adv_embedding, target_embedding)
        source_identity_loss = 1.0 - source_similarity.mean()
        target_identity_loss = 1.0 - target_similarity.mean()
        source_pixel_loss = F.l1_loss(adv, source)
        target_pixel_loss = F.l1_loss(adv, target)
        smoothness_loss = total_variation_loss(delta)
        balance_loss = torch.mean(torch.abs(target_similarity - source_similarity))

        loss = (
            source_weight * source_identity_loss
            + target_weight * target_identity_loss
            + source_pixel_weight * source_pixel_loss
            + target_pixel_weight * target_pixel_loss
            + tv_weight * smoothness_loss
            + balance_weight * balance_loss
        )

        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()

        objective = float(loss.item())
        if objective < best_stats["objective"]:
            best_adv = adv.detach().clone()
            best_stats = {
                "objective": objective,
                "source_similarity": float(source_similarity.mean().item()),
                "target_similarity": float(target_similarity.mean().item()),
                "perturbation_linf": float(delta.detach().abs().amax().item()),
            }

    return best_adv, best_stats


def generate_with_checkpoint(
    source: torch.Tensor,
    target: torch.Tensor,
    checkpoint_path: Path,
    device: torch.device,
    max_perturbation: float,
    embedder: nn.Module,
) -> tuple[torch.Tensor, dict[str, float]]:
    checkpoint = torch.load(checkpoint_path, map_location=device)
    state_dict = checkpoint.get("generator", checkpoint)

    generator = AdvFaceGANGenerator().to(device)
    generator.load_state_dict(state_dict, strict=True)
    generator.eval()

    with torch.no_grad():
        perturbation = torch.tanh(generator(source, target)) * max_perturbation
        adv = torch.clamp(source + perturbation, min=-1.0, max=1.0)
        source_embedding = embedder(source)
        target_embedding = embedder(target)
        adv_embedding = embedder(adv)
        stats = {
            "objective": 0.0,
            "source_similarity": float(cosine_similarity(adv_embedding, source_embedding).mean().item()),
            "target_similarity": float(cosine_similarity(adv_embedding, target_embedding).mean().item()),
            "perturbation_linf": float(perturbation.abs().amax().item()),
        }
    return adv, stats


def build_output_path(output_dir: Path, row: dict[str, str]) -> Path:
    return output_dir / row["victim_identity"] / Path(row["attacker_image"]).name


def main() -> None:
    args = parse_args()
    set_seed(int(args.seed))

    dataset_dir = Path(args.dataset_dir).resolve()
    pair_input = Path(args.pair_input).resolve()
    output_dir = Path(args.output_dir).resolve()
    records_out = Path(args.records_out).resolve()
    checkpoint_path = Path(args.generator_checkpoint).resolve() if args.generator_checkpoint else None
    device = torch.device(args.device)

    if not dataset_dir.exists():
        raise FileNotFoundError(dataset_dir)
    if not pair_input.exists():
        raise FileNotFoundError(pair_input)
    if checkpoint_path is not None and not checkpoint_path.exists():
        raise FileNotFoundError(checkpoint_path)

    rows = load_pair_rows(pair_input)
    output_dir.mkdir(parents=True, exist_ok=True)
    records_out.parent.mkdir(parents=True, exist_ok=True)

    embedder = FaceNetEmbedder(device)
    records: list[dict[str, Any]] = []

    print(f"[INFO] dataset_dir: {dataset_dir}")
    print(f"[INFO] pair_input: {pair_input}")
    print(f"[INFO] output_dir: {output_dir}")
    print(f"[INFO] pairs: {len(rows)}")
    if checkpoint_path is not None:
        print(f"[INFO] generator checkpoint: {checkpoint_path}")
    else:
        print("[INFO] using direct dual-identity optimization (no generator checkpoint provided)")

    for index, row in enumerate(rows):
        source_path = Path(row["attacker_image"]).resolve()
        target_path = Path(row["victim_image"]).resolve()
        output_path = build_output_path(output_dir, row)
        print(f"[PAIR] {index + 1}/{len(rows)} -> {output_path}")

        if output_path.exists() and not args.overwrite:
            records.append(asdict(PairRecord(
                index=index,
                victim_identity=row["victim_identity"],
                attacker_identity=row["attacker_identity"],
                victim_image=str(target_path),
                attacker_image=str(source_path),
                output_image=str(output_path),
                status="skipped",
                message="output already exists",
            )))
            continue

        try:
            source = load_image(source_path, image_size=int(args.image_size), device=device)
            target = load_image(target_path, image_size=int(args.image_size), device=device)

            if checkpoint_path is not None:
                adv, stats = generate_with_checkpoint(
                    source=source,
                    target=target,
                    checkpoint_path=checkpoint_path,
                    device=device,
                    max_perturbation=float(args.max_perturbation),
                    embedder=embedder,
                )
            else:
                adv, stats = optimize_dual_identity_image(
                    source=source,
                    target=target,
                    embedder=embedder,
                    steps=int(args.steps),
                    lr=float(args.lr),
                    max_perturbation=float(args.max_perturbation),
                    source_weight=float(args.source_weight),
                    target_weight=float(args.target_weight),
                    source_pixel_weight=float(args.source_pixel_weight),
                    target_pixel_weight=float(args.target_pixel_weight),
                    tv_weight=float(args.tv_weight),
                    balance_weight=float(args.balance_weight),
                )

            save_image(adv, output_path, jpeg_quality=int(args.jpeg_quality))
            records.append(asdict(PairRecord(
                index=index,
                victim_identity=row["victim_identity"],
                attacker_identity=row["attacker_identity"],
                victim_image=str(target_path),
                attacker_image=str(source_path),
                output_image=str(output_path),
                status="ok",
                message="generated",
                source_similarity=stats["source_similarity"],
                target_similarity=stats["target_similarity"],
                perturbation_linf=stats["perturbation_linf"],
            )))
        except Exception as exc:  # pragma: no cover - per-sample failures are part of runtime behavior
            records.append(asdict(PairRecord(
                index=index,
                victim_identity=row["victim_identity"],
                attacker_identity=row["attacker_identity"],
                victim_image=str(target_path),
                attacker_image=str(source_path),
                output_image=str(output_path),
                status="failed",
                message=str(exc),
            )))
            print(f"[WARN] failed for pair {index}: {exc}")

    summary = {
        "generator": "advfacegan_native",
        "dataset_dir": str(dataset_dir),
        "pair_input": str(pair_input),
        "output_dir": str(output_dir),
        "records_out": str(records_out),
        "seed": int(args.seed),
        "device": str(device),
        "image_size": int(args.image_size),
        "steps": int(args.steps),
        "lr": float(args.lr),
        "max_perturbation": float(args.max_perturbation),
        "source_weight": float(args.source_weight),
        "target_weight": float(args.target_weight),
        "source_pixel_weight": float(args.source_pixel_weight),
        "target_pixel_weight": float(args.target_pixel_weight),
        "tv_weight": float(args.tv_weight),
        "balance_weight": float(args.balance_weight),
        "generator_checkpoint": str(checkpoint_path) if checkpoint_path is not None else None,
        "num_pairs": len(rows),
        "num_ok": sum(record["status"] == "ok" for record in records),
        "num_skipped": sum(record["status"] == "skipped" for record in records),
        "num_failed": sum(record["status"] == "failed" for record in records),
        "records": records,
    }
    with open(records_out, "w", encoding="utf-8") as handle:
        json.dump(summary, handle, indent=2)

    print(f"[INFO] records written: {records_out}")
    print(f"[INFO] ok={summary['num_ok']} skipped={summary['num_skipped']} failed={summary['num_failed']}")


if __name__ == "__main__":
    main()
